### ISSUE TITLE
Interest in adding celery and celerybeat to repo?

### ISSUE THREAD

**Issue by Cally99** [115design/nuxt-django-postgresql#1]
Hi there, 

I have an enhancement request.
I think this is a great starter template for projects. Would you have any interest in adding celery and celerybeat for background processing to this repo?  It would be quite a powerful starter template.
Thanks

**Comment by 115design** [comment]
@Hey-tom 

Hi Tom,

Thank you for suggesting
That's interesting. I will consider it.

For my reference, Please let me know.
What do you want to achieve with celery and celery-beat?

Thank you

**Comment by Cally99** [comment]
No problem!
I'm using a third party library to update my backend with celerybeat schedules. There's a lot of pre-built functions made for the third party lib and celery with beat handles it for me. I'm planning down the line to spawn a few more apps like this using a different third party service for my backend but with the same frontend. The ultimate goal is to have a frontend that I can easily plugin to another backend running a different service provider easily. I haven't seen any boilerplates using nuxt django and celerybeat on github. I think it's a nice mix of tech!

**Comment by 115design** [comment]
@Hey-tom 

Hi Tom,

Thanks for letting me know.

I added an example of celery implementation to this repository.
I am glad if this implementation match a little bit for your project, but if you like, try it out.

Sorry for the wait.
Thank you.

**Comment by 115design** [comment]
I forgot to write it!

After starting the container,
You can check the log with the following command.

`make log_all`

("Hello celery!" Is displayed on the console every 1 minute)
